### ISSUE TITLE
error with " gengine_quickstart myengine"

### ISSUE THREAD

**Issue by zqian** [ActiDoo/gamification-engine#1]
Hi, all:
I got the following error when executing the line " gengine_quickstart myengine" in the installation instruction:

$ gengine_quickstart myengine
Error: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/quickstart_template'

Any suggestions?

**Comment by msander** [comment]
Sorry, I renamed the folder and forgot to update the script. Fixed :)
Thanks for your report!

**Comment by zqian** [comment]
I am still having the same problem.

**Comment by msander** [comment]
have you updated the package?

pip install -U gamification-engine

or directly the git master:

pip install https://github.com/ActiDoo/gamification-engine/archive/master.zip

**Comment by zqian** [comment]
That does work! Thanks!
