### ISSUE TITLE
Errors at heroku instance

### ISSUE THREAD

**Issue by romdim** [ActiDoo/gamification-engine#11]
When calling progress API for user 2 or 35 (these do exist right now), following error is provided as a response:

{"achievement_errors": {"2": {"id": 2, "error": "Traceback (most recent call last):\n  File \"/app/.heroku/python/lib/python2.7/site-packages/gengine/views.py\", line 92, in ea\n    return Achievement.evaluate(user, achievement[\"id\"])\n  File \"/app/.heroku/python/lib/python2.7/site-packages/gengine/models.py\", line 763, in evaluate\n    return cache_achievement_eval.get_or_create(\"%s_%s\" % (user[\"id\"],achievement_id),generate)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/dogpile/cache/region.py\", line 651, in get_or_create\n    async_creator) as value:\n  File \"/app/.heroku/python/lib/python2.7/site-packages/dogpile/core/dogpile.py\", line 158, in __enter__\n    return self._enter()\n  File \"/app/.heroku/python/lib/python2.7/site-packages/dogpile/core/dogpile.py\", line 98, in _enter\n    generated = self._enter_create(createdtime)\n  File \"/app/.heroku/python/lib/python2.7/site-packages/dogpile/core/dogpile.py\", line 149, in _enter_create\n    created = self.creator()\n  File \"/app/.heroku/python/lib/python2.7/site-packages/dogpile/cache/region.py\", line 619, in gen_value\n    created_value = creator()\n  File \"/app/.heroku/python/lib/python2.7/site-packages/gengine/models.py\", line 686, in generate\n    goal_eval[\"leaderboard\"] = Goal.get_leaderboard(goal, user_ids)\nTypeError: 'NoneType' object does not support item assignment\n"}}, "achievements": {}}

**Comment by feldi88** [comment]
I guess the same reason as in #10. Can you please check again after updating? Thanks!

**Comment by romdim** [comment]
Yes, fixed! Thank you very much!
