### ISSUE TITLE
error initializing database

### ISSUE THREAD

**Issue by philaphil** [ActiDoo/gamification-engine#13]
(env)[user@server mygengine]$ initialize_gengine_db production.ini alembic.ini reset_db=True populate_demo=True
Traceback (most recent call last):
  File "/home/user/www/env/bin/initialize_gengine_db", line 9, in <module>
    load_entry_point('gamification-engine==0.1.36', 'console_scripts', 'initialize_gengine_db')()
  File "/home/user/www/env/lib/python2.6/site-packages/gengine/scripts/initializedb.py", line 58, in main
    from ..models import (
  File "/home/user/www/env/lib/python2.6/site-packages/gengine/models.py", line 294
    existing_users_set = {x["id"] for x in DBSession.execute(select([t_users.c.id]).where(t_users.c.id.in_([user_id,]+friends))).fetchall()}
                                    ^
SyntaxError: invalid syntax

**Comment by feldi88** [comment]
Because of several language structures which are used in the engine, you need Python in version 2.7. So please upgrade your current version. I've added this information to the implementation part of the documentation (see 3354563b3ce6f90bb7a1b2886da3df7ea75ce6c3)

**Comment by philaphil** [comment]
Thanks that worked!
I also had to install funcsigs
and update setuptools
