### ISSUE TITLE
Errors trying to increase_value of a variable for a user

### ISSUE THREAD

**Issue by philaphil** [ActiDoo/gamification-engine#14]
I created a user id 10 and a variable gold and I am trying to add a value to it from the api and getting the following error

ProgrammingError: (psycopg2.ProgrammingError) function concat(unknown, character varying, unknown) does not exist
LINE 3: WHERE goals.condition ILIKE concat(E'%"', variables.name, E'...
                                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
 [SQL: 'SELECT goals.id, goals.name, goals.name_translation_id, goals.condition, goals.evaluation, goals.timespan, goals.group_by_key, goals.group_by_dateformat, goals.goal, goals.operator, goals.maxmin, goals.achievement_id, goals.priority, variables.id AS variable_id \nFROM goals, variables \nWHERE goals.condition ILIKE concat(%(param_1)s, variables.name, %(param_2)s) OR goals.condition ILIKE concat(%(param_3)s, variables.name, %(param_4)s)'] [parameters: {'param_4': "'%", 'param_1': '%"', 'param_3': "%'", 'param_2': '"%'}]

**Comment by philaphil** [comment]
I upgraded from postgres 8.4 to 9.5 and reinstalled the database
 now I am getting a new error on all of my calls

TypeError: 'NoneType' object has no attribute '__getitem__'
TypeError: 'NoneType' object does not support item assignment

**Comment by msander** [comment]
It might be an error in your goal definition (We should implement some rule verification!).
However, I'll look into it more detailed later.

**Comment by msander** [comment]
@philaphil Sorry for the way too late response. Is this still an issue for you? We were mainly working on major rule language improvements during the last months and on stability of the whole engine. The current state is in the develop branch, but tests and docs updates are still todos for the upcoming release.

**Comment by msander** [comment]
Closing this now. In case you still have problems, please open another issue.
