### ISSUE TITLE
ImportError: No module named pbr.core

### ISSUE THREAD

**Issue by dkarlovi** [ActiDoo/gamification-engine#2]
I'm trying to run the setup (to evaluate this project, not a Python developer) and am getting this error: ImportError: No module named pbr.core

Output is after this:

    Installed /tmp/easy_install-9rFuFr/unittest2-1.0.1/traceback2-1.4.0-py2.6.egg
    Searching for linecache2
    Reading http://pypi.python.org/simple/linecache2/
    Best match: linecache2 1.0.0
    Downloading https://pypi.python.org/packages/source/l/linecache2/linecache2-1.0.0.tar.gz#md5=7b25d0289ec36bff1f9e63c4329ce65c
    Processing linecache2-1.0.0.tar.gz
    Running linecache2-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9rFuFr/unittest2-1.0.1/temp/easy_install-ocdJn7/linecache2-1.0.0/egg-dist-tmp-PRQgbe

and a long stack trace after. Is there any way around this?

**Comment by msander** [comment]
I think it looks like a problem installing linecache2, not directly connected to the gamification-engine.
Which python version do you use?

**Comment by dkarlovi** [comment]
Yes, I've gathered that. Python version is 2.6.6, as available on CentOS 6.

**Comment by msander** [comment]
some ideas:
* `pip install -U pbr` or `easy_install -U pbr`
* `pip install -U setuptools` or `easy_install -U setuptools`
* try python 2.7

**Comment by dkarlovi** [comment]
Yes, that worked, thanks.
