### ISSUE TITLE
Can add self as friend

### ISSUE THREAD

**Issue by romdim** [ActiDoo/gamification-engine#3]
After already created a user and trying to update him, himself is prompted to be added as a friend through the admin interface.

**Comment by msander** [comment]
The user should not be added to the many-to-many relation, but should be included in the leaderboards (since you want to compare him to his friends).

Do you still think there is an error and if yes, can you provide detailed steps for reproduction?

**Comment by romdim** [comment]
I hadn't really thought of the leaderboard, it was just odd seeing that I could add myself as a friend.
Steps for reproduction after installation would be:
1. Navigate to http://localhost:6543/admin/user/
2. Create a new user (no input needed) and hit save
3. Click on pencil-edit button
4. Tap on Friends input box -> The new user can be found here to be added as a friend

**Comment by msander** [comment]
Ah okay, those admin interfaces are generated by flask admin. Those at debug are really just meant to be used for debugging / development.

For production usage, use the provided APIs (see Home for a Demo).
