### ISSUE TITLE
Keeping configuration through admin interface under version control

### ISSUE THREAD

**Issue by sr258** [ActiDoo/gamification-engine#39]
Hi,

I'm evaluating gamification-engine for an open source project and it looks very much like what I need. I wonder, however, whether there is a way of keeping the whole configuration you create through the admin interface under version control. Is it possible to export and import the configuration? I know that I could create a database dump, but I would prefer a cleaner option.

**Comment by msander** [comment]
I think the best way would be to implement a "population" script.
Look at /gengine/maintenance/scripts/initializedb::populate_demo for an example.
