### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by romdim** [ActiDoo/gamification-engine#4]
Dogpile seems to need a module named fcntl which only exists on Unix systems.

**Comment by msander** [comment]
Yeah, dogpile.cache is currently Unix-only. You can disable Caching if you don't need it (and delete the dependency).

**Comment by romdim** [comment]
Indeed it works by disabling dogpile.cache.
Thank you very much. This is a very helpful library and I will try to help however I can!
