### ISSUE TITLE
404 Not Found add_or_update_user/<user_id>

### ISSUE THREAD

**Issue by mhsharifi96** [ActiDoo/gamification-engine#41]
hi 
when I request to  rest api on gamification engine   a url 404 Not Found

in my gamification engine, auth is off
for example : `http://127.0.0.1:6543/add_or_update_user/2` and method: `post` and python version is `3.7.3`
respones:
`<html>
    <head>
        <title>404 Not Found</title>
    </head>
    <body>
        <h1>404 Not Found</h1>
  The resource could not be found.
        <br/>
        <br/>
/add_or_update_user/2
        <link rel="stylesheet" type="text/css" href="http://127.0.0.1:6543/_debug_toolbar/static/toolbar/toolbar_button.css">
        <div id="pDebug">
            <div  id="pDebugToolbarHandle">
                <a title="Show Toolbar" id="pShowToolBarButton"
           href="http://127.0.0.1:6543/_debug_toolbar/313339383835303732303837393230" target="pDebugToolbar">&#171; FIXME: Debug Toolbar</a>
            </div>
        </div>
    </body>
</html>`

How to solve this problem?

**Comment by msander** [comment]
fixed in develop
