### ISSUE TITLE
No gengine_quickstart script

### ISSUE THREAD

**Issue by anasakhtar01** [ActiDoo/gamification-engine#59]
I am trying to run the following command according to the docs but in the scripts folder of python there is no gengine_quickstart script to be excuted I am running Python 3.6 32-bit. There are different scripts like gengine_scheduler etc in the scripts folder.

gengine_quickstart mygengine

**Comment by msander** [comment]
Docs are outdated; quickstart is not available anymore.
If someone wants to provide better docs or an up-to-date quickstart script, feel free to create a pull request.
