### ISSUE TITLE
/add_or_update_subject/{user_id} returns 502 bad gateway for a new user_id

### ISSUE THREAD

**Issue by SpirosChadoulos** [ActiDoo/gamification-engine#66]
I tried to use the /add_or_update_subject/{user_id} endpoint to add a new user in the gamification engine, with a new id that matches the one the user has in my application. Instead of adding the new user to the database, the API's response was 502 bad gateway.

**Comment by esvehla1** [comment]
Hi @SpirosChadoulos where you able to get this resolved?  If so did you by chance submit a PR?

**Comment by msander** [comment]
This is fixed in develop.
You have to provide "name" and "subjecttype_id".
