### ISSUE TITLE
Create an installation guide

### ISSUE THREAD

**Issue by ariel17** [ActiDoo/gamification-engine#8]
Greetings from Argentina! I would like to ask you formally an installation guide since the project layout is not intuitive in this case; I usually search for a `requirements.txt` to install using `pip` and an starting point in the documentation about how to spawn the application. 

Thank you very much for your time.
Ariel.

**Comment by feldi88** [comment]
Hi Ariel,

thanks for your interest. In the readme file, there is a short list of usage scenarios (https://github.com/ActiDoo/gamification-engine#usage). Especially, it covers the installation in a development environment. Furthermore, there is a ready-to-use dokku/heroku project available (https://github.com/ActiDoo/gamification-engine-dokku).

Nevertheless, I will extend the documentation with some hints how to install the engine (independed of heroku/dokku) in a production environment.

Matthias

**Comment by msander** [comment]
The requirements file is included in the develop-branch and will be included in the next version.
