### ISSUE TITLE
localhost:9000 -  404 Not Found The resource could not be found.  / 

### ISSUE THREAD

**Issue by ervinalcordo26** [ActiDoo/gamification-engine#86]
I'm trying to install this on docker and i'm getting this error on localhost:9000 after docker compose `build` | `up`.

404 Not Found The resource could not be found.  / 

Is it because of the `--reload` as i haven't executed that?

**Comment by danielrosero** [comment]
> 
> 
> I'm trying to install this on docker and i'm getting this error on localhost:9000 after docker compose `build` | `up`.
> 
> 404 Not Found The resource could not be found. /
> 
> Is it because of the `--reload` as i haven't executed that?

@ervinalcordo26  Did you manage to solve this? Best regards.

**Comment by ervinalcordo26** [comment]
Hey Daniel,

I got the front-end working on my local with the usage #3 approach only just now.
And i didn't use their master but this repo below.
https://github.com/viewpnt1/gamification-engine/tree/docker-support

I'm still figuring out to install on docker deployment.

**Comment by ervinalcordo26** [comment]
@danielrosero Just for an update, I got it also working in docker with the branch above.

**Comment by danielrosero** [comment]
Tried out again, but still getting this error:

`021/10/05 11:47:34 [crit] 33#33: *1 connect() to unix:///run/uwsgi/uwsgi.socket failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi/uwsgi.socket:", host: "localhost:9000"`

I'm trying with 
`docker-compose -f docker-compose.production.yml up -d`

Did you use development or production?

@ervinalcordo26 thank you for your support.

**Comment by ervinalcordo26** [comment]
I used the development. Haven't tried production as of now.
Also in this repo, the front-end code is set in port 6543 and not 9000

**Comment by danielrosero** [comment]
@ervinalcordo26 my bad, was in the wrong branch.
Now I don't even have response from` localhost:6543`

Did you do the` --reload` ? Where do you call that?

Best regards

**Comment by danielrosero** [comment]
Still nothing :/

Is normal that this issue popups when doing `docker-compose up`

`http://localhost:6543/admin/` is not working for me

```
gamification-engine-adminer-1    | [Tue Oct  5 14:45:58 2021] PHP 8.0.11 Development Server (http://[::]:8080) started
: not foundn-engine-python-1     | /usr/src/app/init.sh: line 2:
: No such file or directory1     | /usr/src/app/init.sh: cd: line 3: can't cd to /usr/src/app/
: not foundn-engine-python-1     | /usr/src/app/init.sh: line 4:
gamification-engine-python-1     | /usr/src/app/init.sh: line 49: syntax error: unexpected end of file (expecting "then")
```

**Comment by Koma-bgl** [comment]
@danielrosero I added `pip install gamification-engine` in the DockerFile, still got 404
would you mind sharing your dockerfile?

**Comment by Koma-bgl** [comment]
for those who also got 404, you need to go to `http://localhost:9000/admin/` with the slash at the end

**Comment by mhmdsalahsebai** [comment]
@danielrosero Hi,

when to run `pip install gamification-engine`?

I have the same 502 Bad Gateway issue. after I run `docker-compose up` and visit localhost:9000. thanks
