### ISSUE TITLE
Issues during db initialize

### ISSUE THREAD

**Issue by darkmeiun** [ActiDoo/gamification-engine#9]
during the install steps keep receiving the below:

Traceback (most recent call last):
  File "/bin/initialize_gengine_db", line 9, in <module>
    load_entry_point('gamification-engine==0.1.34', 'console_scripts', 'initialize_gengine_db')()
  File "/usr/lib/python2.7/site-packages/gengine/scripts/initializedb.py", line 58, in main
    from ..models import (
ImportError: cannot import name Property

**Comment by romdim** [comment]
Just found out that due to this: https://github.com/ActiDoo/gamification-engine/commit/822651ea531aec068c19f0bde2f02acbc89cb781
initializedb.py should import AchievementProperty instead of Property
Will make a pull request.. :)

**Comment by feldi88** [comment]
Thanks for your comment. I will check the current master tomorrow and release a new version if there are not any problems.

**Comment by feldi88** [comment]
I just finished the new release and published it (https://github.com/ActiDoo/gamification-engine/releases/tag/v0.1.35). The initialization of the database should now work again.
